version: '3.8'

services:
  sonos_api:
    build:
      context: ./SonosManagerApi
      dockerfile: Dockerfile
    ports:
      - "7134:8080"
    networks:
      - sonos_network

  sonos_client:
    build:
      context: ./sonos-controller-ui
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      - sonos_network

networks:
  sonos_network:
    driver: bridge
